//! Independent vectors generated by executing the pinned Electron color helpers.
//! Never generated from the Rust implementation under test.
use super::*;

#[test]
fn every_pinned_javascript_theme_vector_matches_native_srgb_and_alpha_roles() {
    let fixture: serde_json::Value=serde_json::from_str(include_str!("reference-vectors.json")).unwrap();
    assert_eq!(fixture["revision"],"eaa61eded31b6755d4f30ba8eabc5d905cf817cb");
    assert_eq!(fixture["logic_blob"],"667e88f09bc0edb139fe9933ad38aac9e911a710");
    let catalog=theme_catalog().unwrap();
    let expected:usize=catalog.values().map(|variants|variants.len()*4).sum();
    let cases=fixture["cases"].as_array().unwrap();
    assert_eq!(cases.len(),expected);
    let mut seen=std::collections::BTreeSet::new();
    for case in cases {
        let id=case["id"].as_str().unwrap();
        let variant:ThemeVariant=serde_json::from_value(case["variant"].clone()).unwrap();
        let contrast=case["contrast"].as_u64().unwrap() as u8;
        assert!(seen.insert((id,variant,contrast)),"duplicate reference vector");
        let mut theme=catalog[id][&variant].clone();
        theme.contrast=contrast;
        let actual=ThemeTokens::derive(&theme,variant);
        let label=format!("{id} {variant:?} contrast {contrast}");
        assert!((actual.contrast-case["strength"].as_f64().unwrap()).abs()<1e-12,"{label}: strength");
        for (field,actual) in [("surfaceUnder",actual.surface_under),("panel",actual.panel),
            ("editorBackground",actual.editor_background),("composerFocusBorder",actual.composer_focus_border)] {
            assert_eq!(u64::from(actual),case[field].as_u64().unwrap(),"{label}: {field}");
        }
        let derived=case["derived"].as_object().unwrap();
        assert_eq!(derived.len()+5,actual.colors.len(),"{label}: role inventory");
        for (name,expected) in derived {
            let color=actual.paint(name).unwrap_or_else(||panic!("{label}: missing role {name}"));
            assert_eq!(u64::from(color.rgb),expected["rgb"].as_u64().unwrap(),"{label}: {name} RGB");
            assert!((color.alpha-expected["alpha"].as_f64().unwrap()).abs()<1e-12,"{label}: {name} alpha");
        }
    }
}
